### ISSUE TITLE
Cannot find module 'broccoli-filter'

### ISSUE THREAD

**Issue by jcope2013** [rondale-sc/ember-cli-htmlbars#9]
I am using ember cli and follow the instructions in the latest ember blogpost related to Handlebars 2.0 (http://emberjs.com/blog/2014/10/16/handlebars-update.html)

```
  npm uninstall --save broccoli-ember-hbs-template-compiler
  npm install --save-dev ember-cli-htmlbars
  rm -rf bower_components
  bower install --save handlebars#2.0.0
  bower install --save ember#canary
  bower install
```

and then I run ember serve and I get this stack trace

```
Cannot find module 'broccoli-filter'
 Error: Cannot find module 'broccoli-filter'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous> (/Users/jcope/inbox-dashboard/node_modules/ember-cli-htmlbars/index.js:1:76)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
```

**Comment by pankaj20dec** [comment]
When I am install **mirage** using ember install ember-cli-mirage . Command prompts showing 

Reference error: hashtree is not defined at the 
C:\Windows\System32\node_modules\ember-cli-htmlbars\node_modules\broccoli-filter\node_modules\broccoli-kitchen-sink-helpers
